name: nft
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:  
  fonts:
   - family: outfit
     fonts:
      - asset: assets/Outfit-Regular.ttf    
  uses-material-design: true
  assets:
   - assets/